### ISSUE TITLE
Consider Adding Separate HTML pages for each language as like English

### ISSUE THREAD

**Issue by passionate2023** [DSpeckhals/bible.rs#69] opened 2023-01-20 18:12 UTC
Example

https://el-elupath-elu.in/ link has beautiful search engine for all languages

Please kindly try with a keyword - https://english-bible.el-elupath-elu.in/ and it is beautifully designed

Please check whether each separate HTML bible for all languages and also a similar kind of design which would be more flexible and easy navigation....

**Comment by DSpeckhals** [comment] 2023-08-21 14:09
Duplicate of #66

**Closed by DSpeckhals** 2023-08-21 14:09 UTC
